[package]
name = "electrical_mesurements"
version = "1.0.0"
edition = "2021"
license = "ISC"
description = "Electrical measurements"
repository = "https://github.com/winnietthepooh/ElectricalMesurements"
readme = "README.md"

[dependencies]
petgraph = "0.6.3"
