[package]
name = "electrical_mesurements"
version = "0.6.0"
edition = "2021"
license = "ISC"
description = "Electrical measurements"
repository = "https://github.com/winnietthepooh/ElectricalMesurements"
readme = "README.md"

[dependencies]

[features]
default_math = []
default = ["default_math"]
